% This is used to set the evaluation metrics that to be computed
%
% Author:Xingchen Zhang, Ping Ye, Gang Xiao
% Contact: xingchen.zhang@imperial.ac.uk

function metrics=configMetrics
 
    metricsInformationTheory={struct('name','Cross_entropy'),...
         struct('name','Entropy'),...
         struct('name','FMI'),...
         struct('name','NMI'),...         
         struct('name','Psnr'),...
         struct('name','Qncie'),...
         struct('name','TE'),...
         };

     metricsImageFeature={struct('name','Avg_gradient'),...
           struct('name','Edge_intensity'),...
           struct('name','Qabf'),...
           struct('name','Qp'),...
           struct('name','SD'),...
           struct('name','Spatial_frequency'),...
         };

      metricsStructural={
           struct('name','Qc'),...  
           struct('name','Qw'),...
           struct('name','Qy'),...
           struct('name','MEF_SSIM'),...
         };

       metricsPerception={
           struct('name','Qcb'),...
           struct('name','Qcv'),...
           struct('name','VIF'),...
       };

    metrics = [metricsInformationTheory, metricsImageFeature, metricsStructural, metricsPerception];

end
