% This is used to set the MEF algorithms that to be run 
%
% Author:Xingchen Zhang
% Contact:xingchen.zhang@imperial.ac.uk


function methods=configMethods

     methodMatlab={struct('name','DEM'),...
          struct('name','DSIFT_EF'),...
          struct('name','FMMEF'),...
          struct('name','GD'),...
          struct('name','GFF'),...
          struct('name','MEFAW'),...
          struct('name','MEFCNN'),...
          struct('name','MEFDSIFT'),...
          struct('name','MEFOpt'),...
          struct('name','MGFF'),...       
          struct('name','MTI'),...
          struct('name','PMEF'),...
          struct('name','PWA'),...
          struct('name','SPD_MEF'),...
          };

    methodOthers = {struct('name','IFCNN'),...
       struct('name','MEFNet'),...
       struct('name','Deepfuse'),...
       struct('name','FusionDN'),...
       struct('name','MEF-GAN'),...
       struct('name','PMGI'),...
       struct('name','U2Fusion'),...
       };

    methods = [methodMatlab, methodOthers];
end

